development:
 adapter: postgresql
 database: sinatra-practice-development

test:
 adapter: postgresql
 database: sinatra-practice-test
 username: name

production:
 adapter: postgresql
 database: sinatra-practice-production